import { useEffect, useId, useRef, useState } from 'react'
import { MessageCircle, Send, X } from 'lucide-react'
import { useAuth } from './contexts'
import { sendSupportMessage } from './services/supportChatService'
import './SupportChat.css'

const initialMessage = {
  id: 'welcome',
  role: 'assistant',
  content: "Hi! I'm Giftly Support. Tell me what issue you're facing and I'll help you troubleshoot it.",
}

function SupportChatConversation({ user, isOpen, onClose }) {
  const [messages, setMessages] = useState([initialMessage])
  const [message, setMessage] = useState('')
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState('')
  const [validationError, setValidationError] = useState('')
  const latestMessageRef = useRef(null)
  const nextMessageId = useRef(0)
  const inputId = useId()
  const validationErrorId = useId()

  useEffect(() => {
    if (isOpen) {
      latestMessageRef.current?.scrollIntoView({ behavior: 'smooth', block: 'end' })
    }
  }, [messages, isLoading, error, isOpen])

  const submitMessage = async (event) => {
    event.preventDefault()
    const content = message.trim()

    if (!content) {
      setValidationError('Please enter a message before sending.')
      return
    }

    setValidationError('')
    setError('')
    setMessage('')
    setIsLoading(true)

    const conversationHistory = messages.map(({ role, content: messageContent }) => ({
      role,
      content: messageContent,
    }))
    const userMessage = {
      id: `user-${nextMessageId.current++}`,
      role: 'user',
      content,
    }
    setMessages((currentMessages) => [...currentMessages, userMessage])

    try {
      const response = await sendSupportMessage(content, conversationHistory)
      setMessages((currentMessages) => [
        ...currentMessages,
        {
          id: `assistant-${nextMessageId.current++}`,
          role: 'assistant',
          content: response,
        },
      ])
    } catch (sendError) {
      setError(sendError instanceof Error ? sendError.message : 'Unable to send your message. Please try again.')
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <section className="support-chat" aria-label="Giftly AI Support chat">
      <div className="support-chat-heading">
        <div className="support-chat-avatar" aria-hidden="true">G</div>
        <div className="support-chat-title">
          <h2>Giftly AI Support</h2>
          <p>Mock support assistant · responses are not generated by an AI model</p>
        </div>
        {onClose && (
          <button className="support-close-button" type="button" onClick={onClose} aria-label="Close Giftly AI Support">
            <X size={19} />
          </button>
        )}
      </div>

      <div className="support-messages" aria-live="polite" aria-relevant="additions text">
        {messages.map((chatMessage) => (
          <article className={`support-message ${chatMessage.role}`} key={chatMessage.id}>
            <span className="support-message-sender">
              {chatMessage.role === 'assistant' ? 'Giftly Support' : user?.name || 'You'}
            </span>
            <p>{chatMessage.content}</p>
          </article>
        ))}
        {isLoading && (
          <div className="support-message assistant support-loading" role="status">
            <span className="support-message-sender">Giftly Support</span>
            <p>Preparing a response…</p>
          </div>
        )}
        {error && <p className="support-error" role="alert">{error}</p>}
        <div ref={latestMessageRef} />
      </div>

      <form className="support-composer" onSubmit={submitMessage} noValidate>
        <label className="support-input-label" htmlFor={inputId}>Your message</label>
        <div className="support-input-row">
          <input
            id={inputId}
            type="text"
            value={message}
            onChange={(event) => {
              setMessage(event.target.value)
              if (validationError) setValidationError('')
            }}
            placeholder="Describe the issue you’re facing…"
            autoComplete="off"
            aria-describedby={validationError ? validationErrorId : undefined}
            aria-invalid={Boolean(validationError)}
          />
          <button className="button primary" type="submit" disabled={isLoading} aria-label="Send message">
            <Send size={16} />
            <span>{isLoading ? 'Sending…' : 'Send'}</span>
          </button>
        </div>
        {validationError && <p className="support-validation-error" id={validationErrorId}>{validationError}</p>}
        <p className="support-mock-note">This is a mock support experience. Don’t include payment credentials or gift-card PINs.</p>
      </form>
    </section>
  )
}

export function SupportChatWidget() {
  const { user } = useAuth()
  const [isOpen, setIsOpen] = useState(false)

  if (user?.role !== 'customer') return null

  return (
    <div className="support-widget">
      <div className="support-widget-panel" id="giftly-support-panel" hidden={!isOpen}>
        <SupportChatConversation
          user={user}
          isOpen={isOpen}
          onClose={() => setIsOpen(false)}
        />
      </div>
      <button
        className="support-widget-toggle"
        type="button"
        onClick={() => setIsOpen((open) => !open)}
        aria-label={isOpen ? 'Close Giftly AI Support' : 'Open Giftly AI Support'}
        aria-expanded={isOpen}
        aria-controls="giftly-support-panel"
      >
        {isOpen ? <X size={24} /> : <MessageCircle size={25} />}
      </button>
    </div>
  )
}

export function SupportChatPage() {
  const { user } = useAuth()

  return (
    <main className="page support-page">
      <header className="page-header">
        <p className="eyebrow">Giftly Exchange</p>
        <h1>Giftly Support</h1>
        <p>Describe an issue you’re facing and get help with your Giftly experience.</p>
      </header>
      <SupportChatConversation user={user} isOpen />
    </main>
  )
}
